[pytest]

# Pasta onde os testes estão localizados
testpaths = tests

# Padrão dos nomes dos arquivos de teste
python_files = test_*.py

# Padrão dos nomes das funções de teste
python_functions = test_*
